<?php
$baseDir=dirname(__DIR__);
require_once $baseDir.'/services/ManagerRequestContext.php';
ManagerRequestContext::startSession();
?><!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AnyTour — администрирование</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f6f8;color:#18202a;font:15px/1.4 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.wrap{max-width:1050px;margin:auto;padding:18px}.head{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:16px}.nav{display:flex;gap:12px;flex-wrap:wrap}.card{background:#fff;border-radius:16px;padding:16px;margin-bottom:14px;box-shadow:0 1px 3px #0001}h1,h2,h3{margin:0 0 12px}a{color:#1d4ed8;text-decoration:none}label{display:block;font-size:13px;color:#687281;margin:8px 0 4px}input,select{width:100%;padding:10px;border:1px solid #d8dde3;border-radius:10px;background:#fff;font:inherit}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.grid3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px}.checks{display:flex;flex-wrap:wrap;gap:8px}.checks label{margin:0;background:#f3f4f6;padding:7px 9px;border-radius:9px;color:#18202a}.checks input{width:auto}.btn{border:0;border-radius:10px;padding:10px 13px;background:#111827;color:#fff;cursor:pointer;margin-top:12px}.item{border-top:1px solid #eee;padding:11px 0}.muted{font-size:13px;color:#7b8490}.hint{font-size:13px;color:#5f6874;background:#f7f8fa;border-radius:10px;padding:10px 12px;margin-bottom:12px}.hidden{display:none}.pill{font-size:11px;padding:3px 7px;border-radius:999px;background:#eef1f4}.off{opacity:.55}@media(max-width:700px){.grid,.grid3{grid-template-columns:1fr}.wrap{padding:12px}}
</style></head><body><div class="wrap"><div class="head"><div><h1>Администрирование</h1><div class="muted">Проекты, менеджеры и приоритет заявок</div></div><div class="nav"><a href="./">Диалоги</a><a href="routing.php">Маршрутизация</a></div></div><div id="denied" class="card hidden">Доступно только администратору.</div><div id="app" class="hidden">
<div class="card"><h2>Проекты</h2><div id="projects"></div><h3>Новый / изменить проект</h3><input id="projectId" type="hidden"><div class="grid"><div><label>Код проекта</label><input id="projectKey" placeholder="anytour-spb"></div><div><label>Название</label><input id="projectName" placeholder="AnyTour Санкт-Петербург"></div></div><label><input id="projectActive" type="checkbox" checked style="width:auto"> Активен</label><button id="saveProject" class="btn">Сохранить проект</button></div>
<div class="card"><h2>Менеджеры</h2><div id="managers"></div><h3>Новый / изменить менеджера</h3><input id="managerId" type="hidden"><div class="grid"><div><label>Логин</label><input id="managerLogin"></div><div><label>Имя</label><input id="managerName"></div><div><label>Email</label><input id="managerEmail" type="email"></div><div><label>Роль</label><select id="managerRole"><option value="manager">Менеджер</option><option value="admin">Администратор</option></select></div><div><label>Пароль</label><input id="managerPassword" type="password" placeholder="для нового обязателен; для существующего можно оставить пустым"></div><div><label>Базовый приоритет</label><input id="managerPriority" type="number" value="0"><div class="muted">Чем больше число, тем выше приоритет.</div></div></div><label><input id="managerActive" type="checkbox" checked style="width:auto"> Активен</label><label>Доступ к проектам</label><div id="managerProjects" class="checks"></div><button id="saveManager" class="btn">Сохранить менеджера</button></div>
<div class="card"><h2>Правила приоритета</h2><div class="hint">Сначала применяются обычные права маршрутизации. Среди доступных работающих менеджеров считается: базовый приоритет + совпавшие надбавки. Для 4 MAX-каналов передавайте в старте, например, <b>entry_max_1</b>, <b>entry_max_2</b>, <b>entry_max_3</b>, <b>entry_max_4</b>. В правиле выбирайте «MAX-канал входа» и значение <b>max_1</b> и т. д.</div><div id="priorityRules"></div><h3>Новое / изменить правило</h3><input id="ruleId" type="hidden"><div class="grid3"><div><label>Менеджер</label><select id="ruleManager"></select></div><div><label>Условие</label><select id="ruleType"></select></div><div><label>Значение</label><input id="ruleValue" placeholder="max_1"></div><div><label>Надбавка</label><input id="ruleBonus" type="number" value="0" placeholder="30"></div><div><label>Комментарий</label><input id="ruleComment" placeholder="ведёт канал max_1"></div></div><label><input id="ruleActive" type="checkbox" checked style="width:auto"> Правило включено</label><button id="saveRule" class="btn">Сохранить правило</button></div>
</div></div><script>
const S={csrf:'',manager:null,data:{projects:[],managers:[],sources:[],priority:{rules:[],rule_types:[]}}};const $=id=>document.getElementById(id);async function api(action,data={}){const r=await fetch('api.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,csrf:S.csrf,...data})});return r.json()}
function esc(v){const d=document.createElement('div');d.textContent=v??'';return d.innerHTML}const ruleLabels={project_key:'Проект',source_key:'Источник',platform:'Платформа',entry_channel:'MAX-канал входа',region_id:'Регион',campaign_id:'Кампания'};
async function boot(){const j=await api('me');if(!j.ok||!j.manager||j.manager.role!=='admin'){$('denied').classList.remove('hidden');return}S.csrf=j.csrf;S.manager=j.manager;$('app').classList.remove('hidden');await load()}
async function load(){const j=await api('admin_snapshot');if(!j.ok)return;S.data=j.admin||S.data;render()}
function render(){const d=S.data;$('projects').innerHTML=(d.projects||[]).map(p=>`<div class="item ${Number(p.is_active)?'':'off'}"><b>${esc(p.display_name)}</b> <span class="muted">${esc(p.project_key)}</span> <span class="pill">${Number(p.is_active)?'активен':'выключен'}</span> <a href="#" onclick="editProject(${p.id});return false">изменить</a></div>`).join('')||'<div class="muted">Проектов нет</div>';$('managerProjects').innerHTML=(d.projects||[]).map(p=>`<label><input type="checkbox" value="${p.id}"> ${esc(p.display_name)}</label>`).join('');$('managers').innerHTML=(d.managers||[]).map(m=>{const names=(m.project_ids||[]).map(id=>{const p=d.projects.find(x=>Number(x.id)===Number(id));return p?p.display_name:null}).filter(Boolean);return`<div class="item ${Number(m.is_active)?'':'off'}"><b>${esc(m.display_name||m.login)}</b> <span class="muted">${esc(m.login)}</span> <span class="pill">${esc(m.role)}</span> <span class="pill">приоритет ${Number(m.priority||0)}</span><br><span class="muted">${esc(names.join(', ')||'без проектов')}</span> <a href="#" onclick="editManager(${m.id});return false">изменить</a></div>`}).join('')||'<div class="muted">Менеджеров нет</div>';
$('ruleManager').innerHTML=(d.managers||[]).filter(m=>Number(m.is_active)).map(m=>`<option value="${m.id}">${esc(m.display_name||m.login)}</option>`).join('');const types=(d.priority?.rule_types||['project_key','source_key','platform','entry_channel','region_id','campaign_id']);$('ruleType').innerHTML=types.map(t=>`<option value="${esc(t)}">${esc(ruleLabels[t]||t)}</option>`).join('');$('priorityRules').innerHTML=(d.priority?.rules||[]).map(r=>{const m=(d.managers||[]).find(x=>Number(x.id)===Number(r.manager_id));return`<div class="item ${Number(r.is_active)?'':'off'}"><b>${esc(m?.display_name||m?.login||('Менеджер #'+r.manager_id))}</b> · ${esc(ruleLabels[r.rule_type]||r.rule_type)} = <b>${esc(r.rule_value)}</b> → <b>${Number(r.bonus)>=0?'+':''}${Number(r.bonus)}</b> <span class="pill">${Number(r.is_active)?'включено':'выключено'}</span>${r.comment?`<br><span class="muted">${esc(r.comment)}</span>`:''} <a href="#" onclick="editRule(${r.id});return false">изменить</a></div>`}).join('')||'<div class="muted">Правил пока нет</div>'}
window.editProject=id=>{const p=S.data.projects.find(x=>Number(x.id)===Number(id));if(!p)return;$('projectId').value=p.id;$('projectKey').value=p.project_key;$('projectName').value=p.display_name;$('projectActive').checked=Number(p.is_active)===1};
window.editManager=id=>{const m=S.data.managers.find(x=>Number(x.id)===Number(id));if(!m)return;$('managerId').value=m.id;$('managerLogin').value=m.login;$('managerName').value=m.display_name||'';$('managerEmail').value=m.email||'';$('managerRole').value=m.role||'manager';$('managerPassword').value='';$('managerPriority').value=Number(m.priority||0);$('managerActive').checked=Number(m.is_active)===1;document.querySelectorAll('#managerProjects input').forEach(x=>x.checked=(m.project_ids||[]).map(Number).includes(Number(x.value)))};
window.editRule=id=>{const r=(S.data.priority?.rules||[]).find(x=>Number(x.id)===Number(id));if(!r)return;$('ruleId').value=r.id;$('ruleManager').value=r.manager_id;$('ruleType').value=r.rule_type;$('ruleValue').value=r.rule_value;$('ruleBonus').value=Number(r.bonus||0);$('ruleComment').value=r.comment||'';$('ruleActive').checked=Number(r.is_active)===1};
$('saveProject').onclick=async()=>{const j=await api('save_project',{project_id:Number($('projectId').value||0),project_key:$('projectKey').value,display_name:$('projectName').value,is_active:$('projectActive').checked?1:0});if(j.ok){$('projectId').value='';$('projectKey').value='';$('projectName').value='';await load()}else alert('Не удалось сохранить проект')};
$('saveManager').onclick=async()=>{const project_ids=[...document.querySelectorAll('#managerProjects input:checked')].map(x=>Number(x.value));const j=await api('save_manager',{manager_id:Number($('managerId').value||0),login:$('managerLogin').value,display_name:$('managerName').value,email:$('managerEmail').value,role:$('managerRole').value,password:$('managerPassword').value,priority:Number($('managerPriority').value||0),is_active:$('managerActive').checked?1:0,project_ids});if(j.ok){$('managerId').value='';$('managerLogin').value='';$('managerName').value='';$('managerEmail').value='';$('managerPassword').value='';$('managerPriority').value=0;await load()}else alert('Не удалось сохранить менеджера')};
$('saveRule').onclick=async()=>{const j=await api('save_priority_rule',{rule_id:Number($('ruleId').value||0),manager_id:Number($('ruleManager').value||0),rule_type:$('ruleType').value,rule_value:$('ruleValue').value,bonus:Number($('ruleBonus').value||0),comment:$('ruleComment').value,is_active:$('ruleActive').checked?1:0});if(j.ok){$('ruleId').value='';$('ruleValue').value='';$('ruleBonus').value=0;$('ruleComment').value='';$('ruleActive').checked=true;await load()}else alert('Не удалось сохранить правило')};
boot();
</script></body></html>