<?php
session_name('anytour_manager_panel');
session_set_cookie_params(['lifetime'=>60*60*12,'path'=>'/max-search/manager/','secure'=>true,'httponly'=>true,'samesite'=>'Lax']);
session_start();
?><!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AnyTour — администрирование</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f6f8;color:#18202a;font:15px/1.4 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.wrap{max-width:1050px;margin:auto;padding:18px}.head{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:16px}.nav{display:flex;gap:12px;flex-wrap:wrap}.card{background:#fff;border-radius:16px;padding:16px;margin-bottom:14px;box-shadow:0 1px 3px #0001}h1,h2,h3{margin:0 0 12px}a{color:#1d4ed8;text-decoration:none}label{display:block;font-size:13px;color:#687281;margin:8px 0 4px}input,select{width:100%;padding:10px;border:1px solid #d8dde3;border-radius:10px;background:#fff;font:inherit}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.checks{display:flex;flex-wrap:wrap;gap:8px}.checks label{margin:0;background:#f3f4f6;padding:7px 9px;border-radius:9px;color:#18202a}.checks input{width:auto}.btn{border:0;border-radius:10px;padding:10px 13px;background:#111827;color:#fff;cursor:pointer;margin-top:12px}.item{border-top:1px solid #eee;padding:11px 0}.muted{font-size:13px;color:#7b8490}.hidden{display:none}.pill{font-size:11px;padding:3px 7px;border-radius:999px;background:#eef1f4}.off{opacity:.55}@media(max-width:700px){.grid{grid-template-columns:1fr}.wrap{padding:12px}}
</style></head><body><div class="wrap"><div class="head"><div><h1>Администрирование</h1><div class="muted">Проекты и менеджеры</div></div><div class="nav"><a href="./">Диалоги</a><a href="routing.php">Маршрутизация</a></div></div><div id="denied" class="card hidden">Доступно только администратору.</div><div id="app" class="hidden"><div class="card"><h2>Проекты</h2><div id="projects"></div><h3>Новый / изменить проект</h3><input id="projectId" type="hidden"><div class="grid"><div><label>Код проекта</label><input id="projectKey" placeholder="anytour-spb"></div><div><label>Название</label><input id="projectName" placeholder="AnyTour Санкт-Петербург"></div></div><label><input id="projectActive" type="checkbox" checked style="width:auto"> Активен</label><button id="saveProject" class="btn">Сохранить проект</button></div><div class="card"><h2>Менеджеры</h2><div id="managers"></div><h3>Новый / изменить менеджера</h3><input id="managerId" type="hidden"><div class="grid"><div><label>Логин</label><input id="managerLogin"></div><div><label>Имя</label><input id="managerName"></div><div><label>Email</label><input id="managerEmail" type="email"></div><div><label>Роль</label><select id="managerRole"><option value="manager">Менеджер</option><option value="admin">Администратор</option></select></div><div><label>Пароль</label><input id="managerPassword" type="password" placeholder="для нового обязателен; для существующего можно оставить пустым"></div></div><label><input id="managerActive" type="checkbox" checked style="width:auto"> Активен</label><label>Доступ к проектам</label><div id="managerProjects" class="checks"></div><button id="saveManager" class="btn">Сохранить менеджера</button></div></div></div><script>
const S={csrf:'',manager:null,data:{projects:[],managers:[]}};const $=id=>document.getElementById(id);async function api(action,data={}){const r=await fetch('api.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,csrf:S.csrf,...data})});return r.json()}
function esc(v){const d=document.createElement('div');d.textContent=v??'';return d.innerHTML}async function boot(){const j=await api('me');if(!j.ok||!j.manager||j.manager.role!=='admin'){$('denied').classList.remove('hidden');return}S.csrf=j.csrf;S.manager=j.manager;$('app').classList.remove('hidden');await load()}
async function load(){const j=await api('admin_snapshot');if(!j.ok)return;S.data=j.admin||{projects:[],managers:[]};render()}
function render(){const d=S.data;$('projects').innerHTML=d.projects.map(p=>`<div class="item ${Number(p.is_active)?'':'off'}"><b>${esc(p.display_name)}</b> <span class="muted">${esc(p.project_key)}</span> <span class="pill">${Number(p.is_active)?'активен':'выключен'}</span> <a href="#" onclick="editProject(${p.id});return false">изменить</a></div>`).join('')||'<div class="muted">Проектов нет</div>';$('managerProjects').innerHTML=d.projects.map(p=>`<label><input type="checkbox" value="${p.id}"> ${esc(p.display_name)}</label>`).join('');$('managers').innerHTML=d.managers.map(m=>{const names=(m.project_ids||[]).map(id=>{const p=d.projects.find(x=>Number(x.id)===Number(id));return p?p.display_name:null}).filter(Boolean);return`<div class="item ${Number(m.is_active)?'':'off'}"><b>${esc(m.display_name||m.login)}</b> <span class="muted">${esc(m.login)}</span> <span class="pill">${esc(m.role)}</span><br><span class="muted">${esc(names.join(', ')||'без проектов')}</span> <a href="#" onclick="editManager(${m.id});return false">изменить</a></div>`}).join('')||'<div class="muted">Менеджеров нет</div>'}
window.editProject=id=>{const p=S.data.projects.find(x=>Number(x.id)===Number(id));if(!p)return;$('projectId').value=p.id;$('projectKey').value=p.project_key;$('projectName').value=p.display_name;$('projectActive').checked=Number(p.is_active)===1};window.editManager=id=>{const m=S.data.managers.find(x=>Number(x.id)===Number(id));if(!m)return;$('managerId').value=m.id;$('managerLogin').value=m.login;$('managerName').value=m.display_name||'';$('managerEmail').value=m.email||'';$('managerRole').value=m.role||'manager';$('managerPassword').value='';$('managerActive').checked=Number(m.is_active)===1;document.querySelectorAll('#managerProjects input').forEach(x=>x.checked=(m.project_ids||[]).some(v=>Number(v)===Number(x.value)))};
$('saveProject').onclick=async()=>{const j=await api('save_project',{project_id:Number($('projectId').value||0),project_key:$('projectKey').value,display_name:$('projectName').value,is_active:$('projectActive').checked});if(j.ok){$('projectId').value='';$('projectKey').value='';$('projectName').value='';$('projectActive').checked=true;await load()}else alert('Не удалось сохранить проект: '+(j.error||''))};$('saveManager').onclick=async()=>{const project_ids=[...document.querySelectorAll('#managerProjects input:checked')].map(x=>Number(x.value));const j=await api('save_manager',{manager_id:Number($('managerId').value||0),login:$('managerLogin').value,display_name:$('managerName').value,email:$('managerEmail').value,role:$('managerRole').value,password:$('managerPassword').value,is_active:$('managerActive').checked,project_ids});if(j.ok){$('managerId').value='';$('managerLogin').value='';$('managerName').value='';$('managerEmail').value='';$('managerPassword').value='';$('managerRole').value='manager';$('managerActive').checked=true;await load()}else alert('Не удалось сохранить менеджера: '+(j.error||''))};boot();
</script></body></html>
