<?php
$baseDir=dirname(__DIR__);
require_once __DIR__.'/lib/ManagerHttp.php';
ManagerHttp::start();
$httpClientVersion=(string)(@filemtime(__DIR__.'/assets/manager-http-client.js')?:1);
$adminJsVersion=(string)(@filemtime(__DIR__.'/assets/admin.js')?:1);
?><!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AnyTour — администрирование</title><link rel="stylesheet" href="assets/admin.css"></head><body><div class="wrap"><div class="head"><div><h1>Администрирование</h1><div class="muted">Проекты, менеджеры и приоритет заявок</div></div><div class="nav"><a href="./">Диалоги</a><a href="routing.php">Маршрутизация</a><a href="pipeline-admin.php">Этапы и теги продаж</a></div></div><div id="denied" class="card hidden">Доступно только администратору.</div><div id="app" class="hidden">
<div class="card"><h2>Проекты</h2><div id="projects"></div><h3>Новый / изменить проект</h3><input id="projectId" type="hidden"><div class="grid"><div><label>Код проекта</label><input id="projectKey" placeholder="anytour-spb"></div><div><label>Название</label><input id="projectName" placeholder="AnyTour Санкт-Петербург"></div></div><label><input id="projectActive" type="checkbox" checked style="width:auto"> Активен</label><button id="saveProject" class="btn">Сохранить проект</button><div id="projectFormStatus" class="formStatus" role="status" aria-live="polite"></div></div>
<div class="card"><h2>Менеджеры</h2><div id="managers"></div><h3>Новый / изменить менеджера</h3><input id="managerId" type="hidden"><div class="grid"><div><label>Логин</label><input id="managerLogin"></div><div><label>Имя</label><input id="managerName"></div><div><label>Email</label><input id="managerEmail" type="email"></div><div><label>Роль</label><select id="managerRole"><option value="manager">Менеджер</option><option value="admin">Администратор</option></select></div><div><label>Пароль</label><input id="managerPassword" type="password" placeholder="для нового обязателен; для существующего можно оставить пустым"></div><div><label>Базовый приоритет</label><input id="managerPriority" type="number" value="0"><div class="muted">Чем больше число, тем выше приоритет.</div></div></div><label><input id="managerActive" type="checkbox" checked style="width:auto"> Активен</label><label>Доступ к проектам</label><div id="managerProjects" class="checks"></div><button id="saveManager" class="btn">Сохранить менеджера</button><div id="managerFormStatus" class="formStatus" role="status" aria-live="polite"></div></div>
<div class="card"><h2>Правила приоритета</h2><div class="hint">Сначала применяются обычные права маршрутизации. Среди доступных работающих менеджеров считается: базовый приоритет + совпавшие надбавки. Для 4 MAX-каналов передавайте в старте, например, <b>entry_max_1</b>, <b>entry_max_2</b>, <b>entry_max_3</b>, <b>entry_max_4</b>. В правиле выбирайте «MAX-канал входа» и значение <b>max_1</b> и т. д.</div><div id="priorityRules"></div><h3>Новое / изменить правило</h3><input id="ruleId" type="hidden"><div class="grid3"><div><label>Менеджер</label><select id="ruleManager"></select></div><div><label>Условие</label><select id="ruleType"></select></div><div><label>Значение</label><input id="ruleValue" placeholder="max_1"></div><div><label>Надбавка</label><input id="ruleBonus" type="number" value="0" placeholder="30"></div><div><label>Комментарий</label><input id="ruleComment" placeholder="ведёт канал max_1"></div></div><label><input id="ruleActive" type="checkbox" checked style="width:auto"> Правило включено</label><button id="saveRule" class="btn">Сохранить правило</button><div id="ruleFormStatus" class="formStatus" role="status" aria-live="polite"></div></div>
<div class="card"><h2>Журнал изменений</h2><div class="hint">Последние административные изменения. Показываются только безопасные сводные данные без паролей и полных before/after снимков.</div><div id="audit" class="auditList"></div></div>
</div></div><script src="assets/manager-http-client.js?v=<?=htmlspecialchars($httpClientVersion,ENT_QUOTES,'UTF-8')?>"></script><script src="assets/admin.js?v=<?=htmlspecialchars($adminJsVersion,ENT_QUOTES,'UTF-8')?>"></script></body></html>