<?php
$baseDir=dirname(__DIR__);require_once $baseDir.'/config.php';require_once $baseDir.'/maxsearchclass.php';require_once $baseDir.'/services/ManagerRequestContext.php';require_once $baseDir.'/services/ManagerConversationService.php';require_once $baseDir.'/services/ManagerLeadInboxService.php';require_once $baseDir.'/services/SalesPipelineService.php';require_once $baseDir.'/services/LeadTaskService.php';ManagerRequestContext::startSession();header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');
function pipelineOut(array $d,int $s=200):void{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}function pipelineConversation(int $id,int $mid):?array{$d=ManagerConversationService::detail($id,$mid);return$d?(array)($d['conversation']??[]):null;}function pipelineTrip(array $c):array{$chat=$c['external_chat_id']??null;if($chat===null||$chat==='')return[];try{return class_exists('MaxSearchApi')?(array)MaxSearchApi::getAiSearchContext($chat):[];}catch(Throwable $ignored){return[];}}
$data=ManagerRequestContext::jsonBody();$action=(string)($data['action']??'');$m=ManagerRequestContext::manager();if(!$m)pipelineOut(['ok'=>false,'error'=>'unauthorized'],401);if(!ManagerRequestContext::validCsrf(isset($data['csrf'])?(string)$data['csrf']:null))pipelineOut(['ok'=>false,'error'=>'csrf'],403);
if($action==='catalog')pipelineOut(['ok'=>true,'stages'=>SalesPipelineService::stages(true),'tags'=>SalesPipelineService::tags(true),'outcomes'=>SalesPipelineService::outcomeOptions(),'close_reasons'=>SalesPipelineService::closeReasonOptions()]);
if($action==='list'){$queue=(string)($data['queue']??'waiting');$rows=ManagerConversationService::list((int)$m['id'],$queue,200,(string)($data['project_key']??'*'),'',(string)($data['lead_stage_key']??''),(int)($data['lead_tag_id']??0));if(in_array($queue,['waiting','attention'],true))$rows=array_values(array_filter($rows,fn($r)=>empty($r['delivery_failure_category'])));$rows=ManagerLeadInboxService::decorate($rows);$rows=ManagerLeadInboxService::filter($rows,(string)($data['lead_outcome']??''),(string)($data['search']??''));pipelineOut(['ok'=>true,'conversations'=>array_slice($rows,0,100)]);}
$id=(int)($data['conversation_id']??0);$c=pipelineConversation($id,(int)$m['id']);if(!$c)pipelineOut(['ok'=>false,'error'=>'not_found'],404);$can=ManagerRequestContext::canEditAssignedConversation($c,$m);
if($action==='detail')pipelineOut(['ok'=>true,'can_edit_pipeline'=>$can,'pipeline'=>SalesPipelineService::conversationSnapshot($id),'tasks'=>LeadTaskService::listForConversation($id),'trip'=>pipelineTrip($c),'contact'=>['phone'=>$c['phone']??null,'email'=>$c['email']??null],'source'=>['project'=>$c['project_name']??$c['project_key']??null,'source'=>$c['source_name']??null,'channel'=>$c['channel']??null],'handoff'=>['technical_status'=>$c['status']??null,'manager_name'=>$c['manager_name']??null]]);
if($action==='set_stage'){if(!$can)pipelineOut(['ok'=>false,'error'=>'forbidden'],403);$ok=SalesPipelineService::setStage($id,(string)($data['stage_key']??''));pipelineOut(['ok'=>$ok,'pipeline'=>$ok?SalesPipelineService::conversationSnapshot($id):null],$ok?200:409);}
if($action==='set_tags'){if(!$can)pipelineOut(['ok'=>false,'error'=>'forbidden'],403);$ok=SalesPipelineService::setTags($id,(array)($data['tag_ids']??[]),(int)$m['id']);pipelineOut(['ok'=>$ok,'pipeline'=>$ok?SalesPipelineService::conversationSnapshot($id):null],$ok?200:409);}
if($action==='set_outcome'){if(!$can)pipelineOut(['ok'=>false,'error'=>'forbidden'],403);$ok=SalesPipelineService::setOutcome($id,(string)($data['outcome']??''),isset($data['close_reason'])?(string)$data['close_reason']:null,isset($data['note'])?(string)$data['note']:null,(int)$m['id']);pipelineOut(['ok'=>$ok,'pipeline'=>$ok?SalesPipelineService::conversationSnapshot($id):null],$ok?200:422);}
if($action==='create_task'){if(!$can)pipelineOut(['ok'=>false,'error'=>'forbidden'],403);$assigned=(int)($c['manager_id']??0);$result=LeadTaskService::create($id,(string)($data['title']??''),isset($data['due_at'])?(string)$data['due_at']:null,(int)$m['id'],$assigned>0?$assigned:(int)$m['id']);pipelineOut($result+['tasks'=>!empty($result['ok'])?LeadTaskService::listForConversation($id):null],!empty($result['ok'])?200:422);}
if($action==='set_task_completed'){if(!$can)pipelineOut(['ok'=>false,'error'=>'forbidden'],403);$ok=LeadTaskService::setCompleted($id,(int)($data['task_id']??0),!empty($data['completed']));pipelineOut(['ok'=>$ok,'tasks'=>$ok?LeadTaskService::listForConversation($id):null],$ok?200:404);}
pipelineOut(['ok'=>false,'error'=>'unknown_action'],400);
