<?php
$baseDir=dirname(__DIR__);
require_once __DIR__.'/lib/ManagerHttp.php';
ManagerHttp::start();
if(ManagerHttp::managerId()<=0||!ManagerHttp::manager()){header('Location: ./');exit;}
$csrf=ManagerHttp::csrf(true);
?><!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AnyTour — Web Push</title><style>body{font:16px/1.4 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#f5f6f8;margin:0;padding:24px;color:#18202a}.card{max-width:520px;margin:40px auto;background:#fff;border-radius:16px;padding:24px;box-shadow:0 8px 30px #0001}button{border:0;border-radius:10px;padding:12px 16px;background:#111827;color:#fff;font:inherit}.muted{color:#737d89;margin-top:12px}a{color:#111827}</style></head><body><div class="card"><h2>Уведомления менеджера</h2><p>Включите Web Push на этом устройстве. После этого новые заявки и ответы клиентов смогут приходить даже при закрытой панели.</p><button id="enable">Включить уведомления</button><div id="status" class="muted"></div><p><a href="./">← Вернуться в панель</a></p></div><script>
const csrf=<?=json_encode($csrf,JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?>;
const $=id=>document.getElementById(id);
function b64ToUint8(base64String){const padding='='.repeat((4-base64String.length%4)%4);const base64=(base64String+padding).replace(/-/g,'+').replace(/_/g,'/');const raw=atob(base64);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
function sameBytes(left,right){if(!left||!right)return false;const a=new Uint8Array(left),b=new Uint8Array(right);if(a.length!==b.length)return false;for(let i=0;i<a.length;i++){if(a[i]!==b[i])return false}return true}
async function enable(){try{if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window))throw new Error('Этот браузер не поддерживает Web Push');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Разрешение на уведомления не выдано');const reg=await navigator.serviceWorker.register('sw.js',{scope:'./'});await navigator.serviceWorker.ready;const keyResp=await fetch('push.php?action=key',{credentials:'same-origin',cache:'no-store'});const keyJson=await keyResp.json();if(!keyResp.ok||!keyJson.ok||!keyJson.public_key)throw new Error('Не удалось получить push-ключ');const key=b64ToUint8(keyJson.public_key);let sub=await reg.pushManager.getSubscription();if(sub&&sub.options&&sub.options.applicationServerKey&&!sameBytes(sub.options.applicationServerKey,key)){await sub.unsubscribe();sub=null}if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key});const save=await fetch('push.php',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({action:'subscribe',csrf,subscription:sub.toJSON()})});const saved=await save.json();if(!save.ok||!saved.ok)throw new Error('Не удалось сохранить подписку');$('status').textContent='Готово. Web Push включён на этом устройстве.';await reg.showNotification('AnyTour',{body:'Уведомления включены',tag:'anytour-push-enabled'});}catch(e){$('status').textContent=e.message||'Ошибка включения уведомлений';}}
$('enable').onclick=enable;
</script></body></html>
