<?php
session_name('anytour_manager_panel');
session_set_cookie_params(['lifetime'=>60*60*12,'path'=>'/max-search/manager/','secure'=>true,'httponly'=>true,'samesite'=>'Lax']);
session_start();
?><!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>AnyTour — Workspace V2</title><link rel="stylesheet" href="assets/workspace-v2.css"></head><body><div class="workspace">
<aside class="zone inboxZone"><div class="zoneHead"><div class="brand">Лиды</div><div id="managerName" class="muted">Manager Workspace V2</div><div class="queueTabs"><button data-q="waiting" class="active">Новые</button><button data-q="mine">Мои</button><button data-q="all">Все</button><button data-q="closed">Закрытые</button></div><div class="filterRow"><select id="leadStageFilter" class="filterSelect"><option value="">Все этапы</option></select><select id="leadTagFilter" class="filterSelect"><option value="0">Все теги</option></select><select id="leadOutcomeFilter" class="filterSelect"><option value="">Все исходы</option></select><input id="leadSearch" class="filterInput" type="search" placeholder="Имя, телефон, поездка…" autocomplete="off"></div></div><div id="inboxList" class="inboxList"><div class="empty">Загрузка…</div></div></aside>
<main id="conversationZone" class="zone conversationZone"><div class="zoneHead conversationHead"><div><button id="mobileBack" class="mobileBack actionBtn">‹</button><span id="conversationTitle" class="brand">Выберите лид</span><div id="conversationMeta" class="muted"></div></div><div class="actions"><button id="mobileLeadBtn" class="mobileLeadBtn actionBtn">Карточка</button><span id="conversationActions"></span></div></div><div id="messages" class="messages"><div class="empty">Оригинальная переписка туриста появится здесь</div></div><form id="composer" class="composer hidden"><textarea id="replyText" placeholder="Ответ менеджера"></textarea><button class="sendBtn">Отправить</button></form></main>
<aside id="leadZone" class="zone leadZone"><div class="zoneHead"><div class="brand">Карточка лида</div><div class="muted">Продажи отдельно от технического статуса</div></div><div id="leadCard" class="leadCard"><div class="empty">Выберите лид</div></div></aside>
</div><script src="assets/workspace-v2.js" defer></script></body></html>
