<?php

declare(strict_types=1);
$root=dirname(__DIR__);
$files=['START_HERE.md','AGENTS.md','docs/PRODUCT.md','docs/AUTOPILOT.md','docs/OPERATIONS.md','docs/REPO_MAP.md','docs/ARCHITECTURE.md','docs/REFACTOR_ROADMAP.md'];
$failed=0;$passed=0;
function contractCheck(string $name,bool $ok):void{global$failed,$passed;if($ok){echo "PASS  {$name}\n";$passed++;return;}echo "FAIL  {$name}\n";$failed++;}
foreach($files as $path)contractCheck("exists {$path}",is_file($root.'/'.$path)&&filesize($root.'/'.$path)>0);
$start=(string)@file_get_contents($root.'/START_HERE.md');
$agents=(string)@file_get_contents($root.'/AGENTS.md');
$product=(string)@file_get_contents($root.'/docs/PRODUCT.md');
$autopilot=(string)@file_get_contents($root.'/docs/AUTOPILOT.md');
$ops=(string)@file_get_contents($root.'/docs/OPERATIONS.md');
$map=(string)@file_get_contents($root.'/docs/REPO_MAP.md');
$roadmap=(string)@file_get_contents($root.'/docs/REFACTOR_ROADMAP.md');
$s2=strpos($start,'PR S2');$d1=strpos($start,'PR D1');$d2=strpos($start,'PR D2');$d3=strpos($start,'PR D3');$d4=strpos($start,'PR D4');$d5=strpos($start,'PR D5');$d6=strpos($start,'PR D6');$phaseE=$d6===false?false:strpos($start,'## Phase E',$d6);
contractCheck('start here is the current first-read handoff',strpos($start,'Read this file first')!==false&&strpos($agents,'Read `START_HERE.md` first')!==false&&strpos($autopilot,'Read `START_HERE.md`, then `AGENTS.md`')!==false);
contractCheck('start here records completed phase C and P0',strpos($start,'Phase C Manager technical structure is complete')!==false&&strpos($start,'P0 public AI-log exposure was contained in PR #660')!==false);
contractCheck('start here records the completed independent slice order',$s2!==false&&$d1!==false&&$d2!==false&&$d3!==false&&$d4!==false&&$d5!==false&&$d6!==false&&$phaseE!==false&&$s2<$d1&&$d1<$d2&&$d2<$d3&&$d3<$d4&&$d4<$d5&&$d5<$d6&&$d6<$phaseE);
contractCheck('start here records the current Phase D and E checkpoint',strpos($start,'Phase D is complete through the selected low-risk slices')!==false&&strpos($start,'meal callback contract and update-only runtime slice shipped in PRs #680 and #681')!==false&&strpos($start,"Phase E's read-only handoff inventory and the first two proven consolidations")!==false&&strpos($start,"Anna's healthy green state was naturally confirmed")!==false&&strpos($start,'remaining Phase E inventory was re-audited and no further exact duplicate responsibility was proven')!==false);
contractCheck('city inventory is complete before executable value contract',strpos($start,'`child_*` callback update-only runtime slice shipped in PR #685')!==false&&strpos($start,'free-text child-age update-only runtime slice shipped in PR #689')!==false&&strpos($start,'departure-city contract inventory shipped production-green in PR #691')!==false&&strpos($start,'It changed no runtime behavior. Do not repeat it')!==false&&strpos($start,'No additional runtime slice is currently authorized')!==false&&strpos($start,'next safe item is an executable contract/tests-only PR for departure-city ID normalization')!==false&&strpos($start,'`DepartureCityValueContract`')!==false&&strpos($start,'no-flight ID `99`')!==false&&strpos($start,'Keep the contract disconnected from `WizardCallbackAction`, `StateMessageHandler`, AI application and all runtime writers')!==false&&strpos($start,'missing/pre-start city-step behavior is explicitly fail-closed')!==false&&strpos($start,'Do not change callback payloads, directory lookup, URL/Tourvisor values or behavior')!==false&&strpos($start,'Keep country and date mutations deferred')!==false);
contractCheck('remaining fallback working-hours checks stay independent',strpos($start,'one bounds candidate selection')!==false&&strpos($start,'rechecks policy inside the per-conversation lock')!==false&&strpos($start,'Do not collapse that safety check')!==false);
contractCheck('start here preserves mutation semantic boundaries',strpos($start,'`saveLastValue` updates an existing wizard row')!==false&&strpos($start,'callback payload IDs are not automatically equivalent')!==false&&strpos($start,'preserve `InteractionGuard`')!==false);
contractCheck('live evidence cannot authorize protected changes',strpos($start,'Live evidence can confirm and reprioritize a defect, but it cannot authorize')!==false&&strpos($start,'Changing any of them requires explicit user authorization for that exact change')!==false);
contractCheck('neighbouring projects always need exact authorization',strpos($start,'every exact neighbouring project always requires separate explicit authorization')!==false&&strpos($map,'Do not infer permission from a shared domain')!==false);
contractCheck('start here inherits canonical priority',strpos($start,'Use the canonical priority order in `AGENTS.md`')!==false&&strpos($agents,'## Product priority')!==false);
contractCheck('obsolete roadmap sequence is superseded',strpos($roadmap,'former sequence here is superseded')!==false&&strpos($roadmap,'`START_HERE.md` is the current execution sequence')!==false);
contractCheck('security containment accepts safe denial and cannot roll back',strpos($start,'accepted 403/404 response')!==false&&strpos($start,'Never restore public AI logs')!==false);
contractCheck('every merged sha has deploy tls and webhook gates',strpos($start,'After every merge, before starting another PR')!==false&&strpos($start,'strict MAX TLS on the exact SHA')!==false&&strpos($start,'MAX and Telegram webhook checks succeed')!==false&&strpos($start,'Prefer a new revert PR')!==false);
contractCheck('deploy provenance uses fresh authoritative main',strpos($start,'authoritative current `main` ref')!==false&&strpos($start,'never trust a stale local `origin/main`')!==false);
contractCheck('scope forbids neighbouring project edits',strpos($agents,'Work only inside `pyatkoff/max-search-bot`')!==false&&strpos($map,'Explicitly out of scope')!==false);
contractCheck('metrika and lead mechanism are protected',strpos($agents,'Yandex Metrica counters, goals')!==false&&strpos($agents,'existing lead-sending destination/mechanism')!==false);
contractCheck('live conversations precede roadmap cleanup',strpos($agents,'fresh live conversations')!==false&&strpos($autopilot,'Inspect fresh live conversations first')!==false);
contractCheck('priority keeps UX above roadmap refactor',strpos($agents,'dialogue, search, manager-workspace or responsive UX friction')!==false&&strpos($agents,'roadmap product work')!==false);
contractCheck('handoff keeps timezone and five minute fallback',strpos($product,'10:00–20:00 Europe/Kaliningrad')!==false&&strpos($agents,'10:00–20:00 Europe/Kaliningrad')!==false&&strpos($product,'after 5 minutes without a manager reply')!==false);
contractCheck('manager shift state cannot be auto-corrected',strpos($agents,'operator-controlled manager `is_working` state')!==false&&strpos($ops,'Never auto-enable a manager')!==false);
contractCheck('required CI remains merge gate',strpos($agents,'merge only after required CI is green')!==false&&strpos($autopilot,'Required PR CI must be green')!==false);
contractCheck('production completion requires diagnostics',strpos($ops,'production diagnostics transfer')!==false&&strpos($autopilot,'production diagnostics download')!==false);
contractCheck('canonical snapshots are documented',strpos($ops,'tools/production_snapshot.php')!==false&&strpos($ops,'tools/live_session_snapshot.php')!==false);
contractCheck('visual QA baseline is explicit',strpos($agents,'390, 430, 768 and 1440 CSS px')!==false);
contractCheck('roadmap is not permanent knowledge store',strpos($agents,'issue #55 — current roadmap/checkpoints')!==false&&strpos($autopilot,'Durable rules belong in repository docs')!==false);
echo "\n--------------------------\nTOTAL ".($passed+$failed)." | PASS {$passed} | FAIL {$failed}\n";
exit($failed?1:0);
