<?php

declare(strict_types=1);
$root=dirname(__DIR__);
$workflow=(string)@file_get_contents($root.'/.github/workflows/workspace-v2-visual-qa.yml');
$fixture=(string)@file_get_contents($root.'/tests/visual/workspace-v2-fixture.html');
$layoutSpec=(string)@file_get_contents($root.'/tests/visual/workspace-v2-layout.spec.js');
$kanbanFixture=(string)@file_get_contents($root.'/tests/visual/workspace-v2-kanban-fixture.html');
$activityFixture=(string)@file_get_contents($root.'/tests/visual/workspace-v2-inbox-activity-fixture.html');
$startupFixture=(string)@file_get_contents($root.'/tests/visual/workspace-v2-startup-failure-fixture.html');
$inboxFailureFixture=(string)@file_get_contents($root.'/tests/visual/workspace-v2-inbox-load-failure-fixture.html');
$adminFixture=(string)@file_get_contents($root.'/tests/visual/admin-audit-fixture.html');
$passed=0;$failed=0;
function vqCheck(string $name,bool $ok):void{global$passed,$failed;if($ok){echo "PASS  {$name}\n";$passed++;return;}echo "FAIL  {$name}\n";$failed++;}
vqCheck('visual workflow exists',$workflow!=='');
vqCheck('visual fixture exists',$fixture!=='');
vqCheck('layout assertion spec exists',$layoutSpec!=='');
vqCheck('kanban visual fixture exists',$kanbanFixture!=='');
vqCheck('inbox activity visual fixture exists',$activityFixture!=='');
vqCheck('startup failure visual fixture exists',$startupFixture!=='');
vqCheck('inbox load failure visual fixture exists',$inboxFailureFixture!=='');
vqCheck('admin audit visual fixture exists',$adminFixture!=='');
foreach(['390,844','430,932','768,1024','1440,1000'] as $viewport)vqCheck('captures viewport '.$viewport,strpos($workflow,"--viewport-size='".$viewport."'")!==false);
vqCheck('captures mobile Inbox and secondary zones',strpos($workflow,'390-inbox.png')!==false&&strpos($workflow,'390-conversation.png')!==false&&strpos($workflow,'430-lead.png')!==false&&strpos($workflow,'768-conversation.png')!==false);
vqCheck('captures production-like long chat on mobile and desktop',strpos($workflow,'390-conversation-stress.png')!==false&&strpos($workflow,'1440-conversation-stress.png')!==false&&substr_count($workflow,'stress=chat')>=2);
vqCheck('long chat fixture includes repeated history and media',strpos($fixture,"stress==='chat'")!==false&&strpos($fixture,'round<3')!==false&&strpos($fixture,'attachments')!==false&&strpos($fixture,'data:image/svg+xml')!==false&&strpos($fixture,'hotel photo')!==false);
vqCheck('captures desktop and mobile kanban',strpos($workflow,'390-kanban.png')!==false&&strpos($workflow,'1440-kanban.png')!==false&&strpos($workflow,'workspace-v2-kanban-fixture.html')!==false);
vqCheck('kanban visual evidence includes confirmed sales summary',strpos($kanbanFixture,'Продажи 245')!==false&&strpos($kanbanFixture,'outcomeBadge won')!==false&&strpos($kanbanFixture,'Продажа · 245 000 ₽')!==false);
vqCheck('captures inbox last activity on mobile and desktop',strpos($workflow,'workspace-v2-inbox-activity-fixture.html')!==false&&strpos($workflow,'390-inbox-activity.png')!==false&&strpos($workflow,'1440-inbox-activity.png')!==false&&strpos($activityFixture,'leadActivityTime')!==false&&strpos($activityFixture,'Последняя активность')!==false);
vqCheck('captures startup failure recovery on mobile and desktop',strpos($workflow,'workspace-v2-startup-failure-fixture.html')!==false&&strpos($workflow,'390-startup-failure.png')!==false&&strpos($workflow,'1440-startup-failure.png')!==false&&strpos($startupFixture,'startupFailure')!==false&&strpos($startupFixture,'Попробовать снова')!==false&&strpos($startupFixture,'Нет связи с сервером')!==false);
vqCheck('captures Inbox refresh failure with stale data on mobile and desktop',strpos($workflow,'workspace-v2-inbox-load-failure-fixture.html')!==false&&strpos($workflow,'390-inbox-load-failure.png')!==false&&strpos($workflow,'1440-inbox-load-failure.png')!==false&&strpos($inboxFailureFixture,'inboxLoadStatus error')!==false&&strpos($inboxFailureFixture,'Показаны последние загруженные данные')!==false&&strpos($inboxFailureFixture,'Повторить')!==false&&strpos($inboxFailureFixture,'inboxDataStale')!==false);
vqCheck('captures admin audit on mobile and desktop',strpos($workflow,'admin-audit-fixture.html')!==false&&strpos($workflow,'admin-audit-390.png')!==false&&strpos($workflow,'admin-audit-1440.png')!==false&&strpos($adminFixture,'../../manager/assets/admin.css')!==false&&strpos($adminFixture,'Журнал изменений')!==false&&strpos($adminFixture,'auditRow')!==false);
vqCheck('visual evidence uploads as artifact',strpos($workflow,'actions/upload-artifact@v4')!==false&&strpos($workflow,'visual-artifacts/*.png')!==false);
vqCheck('visual QA is isolated from production',stripos($workflow,'deploy_')===false&&strpos($workflow,'app.anytoour.ru')===false);
vqCheck('workflow only targets manager visual paths',strpos($workflow,"- 'manager/**'")!==false&&strpos($workflow,"- 'tests/visual/**'")!==false);
vqCheck('fixture uses production Workspace V2 styles',strpos($fixture,'../../manager/assets/workspace-v2.css')!==false&&strpos($fixture,'../../manager/assets/workspace-v2-inbox.css')!==false&&strpos($fixture,'../../manager/assets/workspace-v2-mobile.css')!==false&&strpos($fixture,'../../manager/assets/workspace-v2-tasks.css')!==false&&strpos($fixture,'../../manager/assets/workspace-v2-notifications.css')!==false);
vqCheck('visual workflow does not rewrite fixture at runtime',strpos($workflow,'sed -i')===false&&strpos($workflow,"grep -q 'workspace-v2-mobile.css'")!==false);
vqCheck('visual workflow runs browser layout assertions',strpos($workflow,'workspace-v2-layout.spec.js')!==false&&strpos($workflow,'Assert responsive layout contracts')!==false&&strpos($workflow,'@playwright/test@1.55.0')!==false);
vqCheck('layout assertions cover overflow composer bubbles media and desktop zones',strpos($layoutSpec,'expectNoHorizontalOverflow')!==false&&strpos($layoutSpec,"'.composer textarea'")!==false&&strpos($layoutSpec,"'.quickReplies'")!==false&&strpos($layoutSpec,"'.msg.customer'")!==false&&strpos($layoutSpec,"'.msg:has(.attachments)'")!==false&&strpos($layoutSpec,"'.inboxZone'")!==false&&strpos($layoutSpec,"'.conversationZone'")!==false&&strpos($layoutSpec,"'.leadZone'")!==false);
vqCheck('activity fixture uses production inbox and mobile styles',strpos($activityFixture,'../../manager/assets/workspace-v2-inbox.css')!==false&&strpos($activityFixture,'../../manager/assets/workspace-v2-mobile.css')!==false&&strpos($activityFixture,'../../manager/assets/workspace-v2-theme.css')!==false);
vqCheck('startup fixture uses production core inbox notification and mobile styles',strpos($startupFixture,'../../manager/assets/workspace-v2.css')!==false&&strpos($startupFixture,'../../manager/assets/workspace-v2-inbox.css')!==false&&strpos($startupFixture,'../../manager/assets/workspace-v2-notifications.css')!==false&&strpos($startupFixture,'../../manager/assets/workspace-v2-mobile.css')!==false);
vqCheck('Inbox failure fixture uses production inbox and mobile styles',strpos($inboxFailureFixture,'../../manager/assets/workspace-v2.css')!==false&&strpos($inboxFailureFixture,'../../manager/assets/workspace-v2-inbox.css')!==false&&strpos($inboxFailureFixture,'../../manager/assets/workspace-v2-mobile.css')!==false);
vqCheck('fixture covers high-risk responsive states',strpos($fixture,'waitUrgent')!==false&&strpos($fixture,'waitWarn')!==false&&strpos($fixture,'leadTaskCompact overdue')!==false&&strpos($fixture,'leadWaitCompact urgent')!==false&&strpos($fixture,'conversationZone')!==false&&strpos($fixture,'leadZone')!==false);
vqCheck('fixture can expose mobile conversation and lead views',strpos($fixture,"view==='conversation'")!==false&&strpos($fixture,"view==='lead'")!==false&&strpos($fixture,"classList.add('open')")!==false);
vqCheck('kanban fixture uses production board styles',strpos($kanbanFixture,'../../manager/assets/workspace-v2-kanban.css')!==false&&strpos($kanbanFixture,'kanbanMode')!==false&&strpos($kanbanFixture,'kanbanColumn')!==false&&strpos($kanbanFixture,'kanbanCard urgent')!==false);
vqCheck('fixtures have no real production endpoints',strpos($fixture,'app.anytoour.ru')===false&&strpos($fixture,'api.php')===false&&strpos($fixture,'pipeline-api.php')===false&&strpos($kanbanFixture,'app.anytoour.ru')===false&&strpos($kanbanFixture,'api.php')===false&&strpos($kanbanFixture,'pipeline-api.php')===false&&strpos($activityFixture,'app.anytoour.ru')===false&&strpos($activityFixture,'api.php')===false&&strpos($activityFixture,'pipeline-api.php')===false&&strpos($startupFixture,'app.anytoour.ru')===false&&strpos($startupFixture,'api.php')===false&&strpos($startupFixture,'pipeline-api.php')===false&&strpos($inboxFailureFixture,'app.anytoour.ru')===false&&strpos($inboxFailureFixture,'api.php')===false&&strpos($inboxFailureFixture,'pipeline-api.php')===false&&strpos($adminFixture,'app.anytoour.ru')===false&&strpos($adminFixture,'api.php')===false);
echo "\n--------------------------\nTOTAL ".($passed+$failed)." | PASS {$passed} | FAIL {$failed}\n";exit($failed?1:0);