<?php

declare(strict_types=1);
$root=dirname(__DIR__);
$page=(string)file_get_contents($root.'/manager/routing.php');
$js=(string)file_get_contents($root.'/manager/assets/routing.js');
$css=(string)file_get_contents($root.'/manager/assets/routing.css');
$migration=(string)file_get_contents($root.'/migrations/022_source_handling_mode.sql');
$promoMigration=(string)file_get_contents($root.'/migrations/025_source_channel_promo.sql');
$routingService=(string)file_get_contents($root.'/services/RoutingAdminService.php');
$api=(string)file_get_contents($root.'/manager/api.php');
$sourceHandling=(string)file_get_contents($root.'/services/SourceHandlingService.php');
$channelOffer=(string)file_get_contents($root.'/services/ChannelOfferService.php');
$dispatcher=(string)file_get_contents($root.'/services/IncomingUpdateDispatcher.php');
$passed=0;$failed=0;
function checkRouting(string $name,bool $ok):void{global$passed,$failed;if($ok){echo "PASS  $name\n";$passed++;}else{echo "FAIL  $name\n";$failed++;}}
checkRouting('routing shell loads extracted css',strpos($page,'assets/routing.css?v=')!==false&&strpos($page,'<style>')===false);
checkRouting('routing shell loads extracted js',strpos($page,'assets/routing.js?v=')!==false&&strpos($page,'const S=')===false);
checkRouting('source save validation remains in routing module',strpos($js,"missing_source_key")!==false&&strpos($js,"duplicate_source_key")!==false&&strpos($js,"fallback_group_required")!==false);
checkRouting('routing API actions remain unchanged',strpos($js,"api('routing_snapshot'")!==false&&strpos($js,"api('save_group'")!==false&&strpos($js,"api('save_source'")!==false);
checkRouting('group save has inline status surface',strpos($page,'id="groupStatus"')!==false&&strpos($page,'aria-live="polite"')!==false&&strpos($js,"groupStatus('Группа сохранена.','success')")!==false);
checkRouting('group save preserves form on transport failure',strpos($js,"try{j=await api('save_group'")!==false&&strpos($js,"j={ok:false,error:'network_error'}")!==false&&strpos($js,'Данные формы сохранены — повторите попытку.')!==false);
checkRouting('source save recovers button after transport failure',strpos($js,"try{j=await api('save_source'")!==false&&strpos($js,"setFormSaving('source',false);btn.textContent=oldText")!==false&&strpos($js,'sourceErrorText(j.error)')!==false);
checkRouting('routing save buttons reject duplicate submits',strpos($js,'if(S.saving.group||btn.disabled)return')!==false&&strpos($js,'if(S.saving.source||btn.disabled)return')!==false);
checkRouting('routing load has inline status surface',strpos($page,'id="routingStatus"')!==false&&strpos($js,"routingStatus('Загружаем маршрутизацию…','')")!==false);
checkRouting('routing load rejects stale project responses',strpos($js,'loadSeq:0')!==false&&strpos($js,'const seq=++S.loadSeq')!==false&&strpos($js,'if(seq!==S.loadSeq)return')!==false&&strpos($js,"if($('project').value!==key)return")!==false);
checkRouting('routing load preserves current data on transport failure',strpos($js,"try{j=await api('routing_snapshot'")!==false&&strpos($js,'Текущие данные не изменены')!==false);
checkRouting('routing load keeps selected project aligned with rendered snapshot',strpos($js,"loadedProjectKey:''")!==false&&strpos($js,"if(S.loadedProjectKey)$('project').value=S.loadedProjectKey")!==false&&strpos($js,'S.loadedProjectKey=key')!==false);
checkRouting('routing project switch clears stale edit forms',strpos($js,'const projectChanged=S.loadedProjectKey!==\'\'&&S.loadedProjectKey!==key')!==false&&strpos($js,'if(projectChanged){resetGroupForm();resetSourceForm()}')!==false&&strpos($js,'function resetGroupForm()')!==false&&strpos($js,'function resetSourceForm()')!==false);
checkRouting('routing group/source forms expose explicit edit targets and safe cancel controls',strpos($page,'id="groupFormTitle">Новая группа')!==false&&strpos($page,'id="sourceFormTitle">Новый источник')!==false&&strpos($page,'id="cancelGroupEdit"')!==false&&strpos($page,'id="cancelSourceEdit"')!==false&&strpos($page,'Отменить редактирование')!==false);
checkRouting('routing edit helpers name current records without server mutation',strpos($js,'function setGroupEditMode(group=null)')!==false&&strpos($js,'Редактируется группа:')!==false&&strpos($js,'function setSourceEditMode(source=null)')!==false&&strpos($js,'Редактируется источник:')!==false&&strpos($js,"$('cancelGroupEdit').classList.toggle('hidden',!editing)")!==false&&strpos($js,"$('cancelSourceEdit').classList.toggle('hidden',!editing)")!==false);
checkRouting('routing edit selection enters explicit mode',strpos($js,'setGroupEditMode(g)')!==false&&strpos($js,'setSourceEditMode(s)')!==false);
checkRouting('routing edit cancellation is client-side reset only and save guarded',strpos($js,"$('cancelGroupEdit').onclick=()=>{if(editorBusy('group'))return;resetGroupForm()};")!==false&&strpos($js,"$('cancelSourceEdit').onclick=()=>{if(editorBusy('source'))return;resetSourceForm()};")!==false);
checkRouting('routing resets restore create mode after cancel save or project switch',strpos($js,'setGroupEditMode();groupStatus')!==false&&strpos($js,'setSourceEditMode();sourceStatus')!==false&&strpos($js,"if(j.ok){resetGroupForm();groupStatus('Группа сохранена.'")!==false&&strpos($js,"if(j.ok){resetSourceForm();sourceStatus('Источник сохранён.'")!==false);
checkRouting('routing saves are pinned to initiating project',substr_count($js,"const project_key=$('project').value")>=2&&substr_count($js,"if($('project').value!==project_key)return")>=2&&strpos($js,"api('save_group',{project_key,")!==false&&strpos($js,"api('save_source',{project_key,")!==false);
checkRouting('routing boot handles empty project access',strpos($js,'if(!S.projects.length)')!==false&&strpos($js,'Нет доступных проектов для настройки маршрутизации.')!==false);
checkRouting('responsive routing styles remain extracted',strpos($css,'grid-template-columns:1fr 1fr')!==false&&strpos($css,'@media(max-width:700px){.grid{grid-template-columns:1fr}')!==false&&strpos($css,'.wrap{padding:12px}')!==false);
checkRouting('source handling schema defaults safely to AI',strpos($migration,"handling_mode ENUM('ai','manager','ask')")!==false&&strpos($migration,"DEFAULT 'ai'")!==false);
checkRouting('source admin exposes all three start modes',strpos($page,'id="handlingMode"')!==false&&strpos($page,'Сначала AI')!==false&&strpos($page,'Сразу менеджеру')!==false&&strpos($page,'Спросить клиента')!==false);
checkRouting('source admin persists and restores start mode',strpos($js,"$('handlingMode').value=s.handling_mode||'ai'")!==false&&strpos($js,'handling_mode')!==false&&strpos($api,"(string)(\$data['handling_mode']??'ai')")!==false);
checkRouting('source service validates explicit handling modes',strpos($routingService,"['ai','manager','ask']")!==false&&strpos($routingService,'invalid_handling_mode')!==false);
checkRouting('source promo schema defaults to showing channels',strpos($promoMigration,'suppress_channel_offer TINYINT(1) NOT NULL DEFAULT 0')!==false);
checkRouting('source promo migration targets only known own-channel markers',strpos($promoMigration,"'max_anytour_msk'")!==false&&strpos($promoMigration,"'tg_anytour_msk'")!==false&&strpos($promoMigration,"max:anytour-main")!==false);
checkRouting('source admin exposes explicit no-channel-promo flag',strpos($page,'id="suppressChannelOffer"')!==false&&strpos($page,'Не предлагать каналы')!==false);
checkRouting('source admin restores and persists promo flag',strpos($js,"$('suppressChannelOffer').checked=Number(s.suppress_channel_offer)===1")!==false&&strpos($js,'suppress_channel_offer')!==false&&strpos($api,"!empty(\$data['suppress_channel_offer'])")!==false);
checkRouting('source service stores promo flag in snapshot and mutations',strpos($routingService,'s.suppress_channel_offer')!==false&&strpos($routingService,'bool $suppressChannelOffer=false')!==false&&strpos($routingService,'suppress_channel_offer=?')!==false&&strpos($routingService,'handling_mode,suppress_channel_offer,primary_group_id')!==false);
checkRouting('channel promo suppression is explicit source lookup and fails open',strpos($channelOffer,'sourceSuppressesOffer')!==false&&strpos($channelOffer,'s.source_key=?')!==false&&strpos($channelOffer,'return false;')!==false&&strpos($channelOffer,'entryFamily')===false);
checkRouting('ask mode offers manager or self service',strpos($sourceHandling,'source_choice_manager')!==false&&strpos($sourceHandling,'source_choice_ai')!==false&&strpos($sourceHandling,'Позвать менеджера')!==false&&strpos($sourceHandling,'Подобрать тур самостоятельно')!==false);
checkRouting('manager-first reuses canonical handoff queue application without metrika mutation',strpos($sourceHandling,'ManagerHandoffDispatchService::dispatch')!==false&&strpos($sourceHandling,'ManagerHandoffDispatchService::applyQueueDecision')!==false&&strpos($sourceHandling,'ConversationControlService::markWaitingByChat')===false&&strpos($sourceHandling,'queueMetrikaGoal')===false&&strpos($sourceHandling,'MetrikaConversionGoalService')===false);
checkRouting('source policy does not own shift priority or routing mutations',strpos($sourceHandling,'setWorking')===false&&strpos($sourceHandling,'ManagerPriorityService')===false&&strpos($sourceHandling,'RoutingAdminService')===false);
checkRouting('source policy runs before normal AI application',strpos($dispatcher,'SourceHandlingService::handle($incoming)')!==false&&strpos($dispatcher,'SourceHandlingService::handle($incoming)')<strpos($dispatcher,'$this->application->dispatch($incoming)'));
checkRouting('manager choice suppresses AI even when transport fails',strpos($sourceHandling,"self::handoff(\$incoming,\$platform,\$chatId,'source_policy');\n                return true;")!==false&&strpos($sourceHandling,"self::handoff(\$incoming,\$platform,\$chatId,'source_choice');\n                    return true;")!==false);
checkRouting('handoff back restores self service',strpos($sourceHandling,"self::recordChoice(\$platform,\$chatId,self::AI,'handoff_back')")!==false);
echo "\n--------------------------\nTOTAL ".($passed+$failed)." | PASS $passed | FAIL $failed\n";
exit($failed?1:0);
