(()=>{
  const script=document.currentScript;
  const apiUrl=new URL('api.php',script&&script.src?script.src:location.href).toString();
  const storageKey='anytour_consultant_token_v1';
  const host=document.createElement('div');host.id='anytour-consultant-host';document.body.appendChild(host);
  const root=host.attachShadow({mode:'open'});
  root.innerHTML=`<style>
    :host{all:initial}
    *{box-sizing:border-box}
    button,input,textarea{font:inherit}
    .launcher-wrap{position:fixed;right:22px;bottom:22px;z-index:2147483000;display:flex;align-items:center;gap:10px;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Inter,Arial,sans-serif}
    .launcher-label{display:flex;align-items:center;gap:8px;background:rgba(255,255,255,.96);backdrop-filter:blur(18px);color:#102a43;border:1px solid rgba(16,42,67,.08);border-radius:999px;padding:11px 15px;font:700 13px/1.15 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;box-shadow:0 12px 34px rgba(16,42,67,.15);cursor:pointer;transition:.2s ease}
    .launcher-label:hover{transform:translateY(-1px);box-shadow:0 16px 38px rgba(16,42,67,.18)}
    .launcher{position:relative;border:0;border-radius:20px;background:linear-gradient(135deg,#0b7cff,#00a8ff);color:#fff;width:62px;height:62px;display:grid;place-items:center;box-shadow:0 18px 40px rgba(0,122,255,.32);cursor:pointer;transition:.2s ease}
    .launcher:hover{transform:translateY(-2px) scale(1.02)}
    .launcher:before{content:"";position:absolute;inset:8px;border:1px solid rgba(255,255,255,.3);border-radius:15px}
    .launcher svg{width:27px;height:27px;position:relative}
    .panel{position:fixed;right:22px;bottom:98px;z-index:2147483000;width:min(430px,calc(100vw - 28px));height:min(700px,calc(100vh - 130px));background:#f6f9fc;border:1px solid rgba(15,40,66,.08);border-radius:28px;box-shadow:0 28px 80px rgba(23,48,73,.24);overflow:hidden;display:none;flex-direction:column;font:14px/1.45 -apple-system,BlinkMacSystemFont,"Segoe UI",Inter,Arial,sans-serif;color:#102a43}
    .panel.open{display:flex;animation:panelIn .2s ease-out}
    @keyframes panelIn{from{opacity:0;transform:translateY(10px) scale(.985)}to{opacity:1;transform:none}}
    .head{padding:16px 16px 14px;background:linear-gradient(135deg,#083f8f 0%,#0b79e8 55%,#19a7f5 100%);color:#fff;display:flex;justify-content:space-between;align-items:center;gap:12px;position:relative;overflow:hidden}
    .head:after{content:"";position:absolute;width:180px;height:180px;border-radius:50%;right:-70px;top:-100px;background:rgba(255,255,255,.13)}
    .brand{display:flex;align-items:center;gap:11px;min-width:0;position:relative;z-index:1}
    .avatar{width:44px;height:44px;border-radius:15px;display:grid;place-items:center;background:rgba(255,255,255,.18);border:1px solid rgba(255,255,255,.25);box-shadow:inset 0 1px 0 rgba(255,255,255,.2)}
    .avatar svg{width:26px;height:26px}
    .brand-copy{min-width:0}.title{font-weight:800;font-size:15px;letter-spacing:-.1px}.sub{font-size:11.5px;color:rgba(255,255,255,.82);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:270px;margin-top:2px}
    .head-actions{display:flex;align-items:center;gap:4px;position:relative;z-index:1}
    .icon-btn{border:0;background:rgba(255,255,255,.14);color:#fff;width:36px;height:36px;border-radius:12px;font-size:22px;line-height:1;cursor:pointer;transition:.18s}.icon-btn:hover{background:rgba(255,255,255,.22)}
    .status{display:flex;align-items:center;gap:7px;padding:8px 15px;font-size:11.5px;color:#59708a;background:rgba(255,255,255,.94);border-bottom:1px solid #e9eef4}
    .status:before{content:"";width:7px;height:7px;border-radius:50%;background:#27ae60;box-shadow:0 0 0 3px rgba(39,174,96,.12)}
    .status.manager{color:#087443}.status.waiting{color:#9a6700}.status.waiting:before{background:#f0a500;box-shadow:0 0 0 3px rgba(240,165,0,.12)}.status.typing{color:#52677c}.status.typing:before{background:#6c8bab}.status.error{color:#b42318}.status.error:before{background:#d92d20}
    .messages{flex:1;overflow:auto;padding:15px 14px 18px;display:flex;flex-direction:column;gap:10px;overscroll-behavior:contain;scroll-behavior:smooth}
    .welcome{background:linear-gradient(180deg,#ffffff 0%,#fbfdff 100%);border:1px solid #e5edf5;border-radius:20px;padding:16px 15px;color:#4f667d;box-shadow:0 8px 28px rgba(27,66,101,.06)}
    .welcome-kicker{display:inline-flex;align-items:center;gap:6px;background:#eaf5ff;color:#0b6ec8;border-radius:999px;padding:5px 9px;font-size:10.5px;font-weight:800;text-transform:uppercase;letter-spacing:.04em}
    .welcome h3{margin:10px 0 6px;color:#102a43;font-size:18px;line-height:1.2;letter-spacing:-.3px}.welcome p{margin:0;font-size:13px;line-height:1.5}
    .quick-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:13px}
    .quick-actions button{border:1px solid #dbe8f4;background:#fff;color:#173b5d;border-radius:13px;padding:10px 11px;text-align:left;font-size:12px;line-height:1.25;font-weight:700;cursor:pointer;transition:.18s}.quick-actions button:hover{border-color:#b7d7f3;background:#f7fbff;transform:translateY(-1px)}
    .msg{max-width:86%;padding:10px 12px;border-radius:17px;background:#fff;white-space:pre-wrap;word-break:break-word;box-shadow:0 2px 8px rgba(27,66,101,.05);border:1px solid #e7eef5}
    .msg.me{align-self:flex-end;background:linear-gradient(135deg,#0b7cff,#1498f2);color:#fff;border-color:transparent;box-shadow:0 8px 18px rgba(11,124,255,.18);border-bottom-right-radius:6px}.msg.manager{background:#eefaf3;border-color:#d7f0e1;border-bottom-left-radius:6px}.msg:not(.me):not(.manager){border-bottom-left-radius:6px}
    .who{font-size:10px;color:#8191a2;margin-top:5px}.msg.me .who{color:rgba(255,255,255,.72)}
    .buttons{display:flex;flex-direction:column;gap:7px;margin-top:9px}.buttons button,.buttons a{display:block;width:100%;border:1px solid #d7e4f0;border-radius:12px;background:#fff;padding:9px 11px;text-align:center;color:#173b5d;text-decoration:none;font:700 12px/1.2 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;cursor:pointer}.buttons button:hover,.buttons a:hover{background:#f6fbff}
    .contact-card{max-width:94%;background:#fff;border:1px solid #dfe9f2;border-radius:18px;padding:14px;box-shadow:0 8px 24px rgba(27,66,101,.06)}.contact-card .ask{font-weight:800;margin-bottom:4px;color:#153653}.contact-card .hint{font-size:12px;color:#667b90;margin-bottom:10px}.contact-row{display:flex;gap:7px;margin-top:7px}.contact-row input{min-width:0;flex:1;border:1px solid #ccdbe8;border-radius:12px;padding:10px 11px;font:inherit;outline:none;background:#fbfdff}.contact-row input:focus{border-color:#72b5ed;box-shadow:0 0 0 3px rgba(11,124,255,.08)}.contact-actions{display:flex;gap:7px;margin-top:9px}.contact-actions button{border:0;border-radius:12px;padding:10px 12px;font:700 12px/1.2 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;cursor:pointer}.contact-save{background:linear-gradient(135deg,#0b7cff,#1498f2);color:#fff}.contact-skip{background:#eef3f8;color:#475d73}.contact-note{font-size:11px;color:#667b90;margin-top:7px}
    .composer-wrap{background:rgba(255,255,255,.96);border-top:1px solid #e4ebf2;padding:10px 11px 11px;backdrop-filter:blur(16px)}
    .composer-hint{font-size:10.5px;color:#8b9cac;margin:0 4px 7px}.composer{display:flex;gap:8px;align-items:flex-end}.composer textarea{flex:1;border:1px solid #ccdae7;border-radius:16px;padding:11px 12px;resize:none;min-height:46px;max-height:112px;font:14px/1.35 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;outline:none;background:#fbfdff;color:#153653}.composer textarea:focus{border-color:#6db2ec;box-shadow:0 0 0 3px rgba(11,124,255,.08);background:#fff}.composer textarea::placeholder{color:#94a4b5}.composer button{border:0;border-radius:15px;background:linear-gradient(135deg,#0b7cff,#1498f2);color:#fff;width:46px;height:46px;display:grid;place-items:center;cursor:pointer;box-shadow:0 9px 18px rgba(11,124,255,.2)}.composer button svg{width:19px;height:19px}.composer button:disabled{opacity:.55;box-shadow:none}
    @media(max-width:520px){.launcher-wrap{right:14px;bottom:14px}.launcher-label{display:none}.launcher{width:58px;height:58px;border-radius:18px}.panel{inset:0;width:100vw;height:100dvh;max-height:none;border-radius:0;border:0}.head{padding:calc(max(14px,env(safe-area-inset-top)) + 2px) 14px 14px}.sub{max-width:220px}.messages{padding:13px 12px 16px}.welcome{padding:15px 14px}.quick-actions{grid-template-columns:1fr}.composer-wrap{padding-bottom:max(11px,env(safe-area-inset-bottom))}.contact-row{flex-direction:column}}
  </style>
  <div class="launcher-wrap">
    <button class="launcher-label" type="button"><span>🌴</span><span>Подобрать тур с AI</span></button>
    <button class="launcher" aria-label="Открыть онлайн-консультант" type="button"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M7 18.2 3.8 20l.9-3.6A8 8 0 1 1 7 18.2Z" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"/><path d="M8 10h8M8 13.5h5" stroke="currentColor" stroke-width="1.9" stroke-linecap="round"/></svg></button>
  </div>
  <section class="panel" role="dialog" aria-label="Онлайн-консультант AnyTour">
    <div class="head"><div class="brand"><div class="avatar"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 3c2.2 2.5 3.2 5.2 2.8 8.2M11.5 5.2C9 6.1 7.2 8 6.2 10.6M12 12c2.7.7 4.8 2.2 6.3 4.7M12 12c-2.8.6-5 2.2-6.6 4.8M12 12v8" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg></div><div class="brand-copy"><div class="title">AnyTour · помощник по отдыху</div><div class="sub">Подберу варианты и подключу менеджера, когда нужно</div></div></div><div class="head-actions"><button class="icon-btn close" aria-label="Закрыть" type="button">×</button></div></div>
    <div class="status">Готов помочь</div>
    <div class="messages"><div class="welcome"><div class="welcome-kicker">AI-помощник AnyTour</div><h3>Расскажите, каким должен быть ваш отдых</h3><p>Можно написать всё одной фразой — направление, даты, состав туристов, бюджет и пожелания. Я соберу параметры и помогу перейти к подходящим вариантам.</p><div class="quick-actions"><button type="button" data-prompt="Хочу подобрать тур по бюджету">💰 Подобрать по бюджету</button><button type="button" data-prompt="Посоветуйте, куда лучше поехать">✨ Посоветуйте направление</button><button type="button" data-prompt="Хочу тур для семьи с детьми">👨‍👩‍👧 Для семьи с детьми</button><button type="button" data-prompt="Хочу подключить менеджера">👩‍💼 Позвать менеджера</button></div></div></div>
    <div class="composer-wrap"><div class="composer-hint">Например: «Турция в сентябре, 2 взрослых + ребёнок, до 250 000 ₽»</div><form class="composer"><textarea rows="1" placeholder="Опишите пожелания к отдыху…"></textarea><button aria-label="Отправить"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m4 12 15-7-5.5 14-2.2-5.8L4 12Z" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"/></svg></button></form></div>
  </section>`;

  const $=s=>root.querySelector(s),launcher=$('.launcher'),launcherLabel=$('.launcher-label'),panel=$('.panel'),messages=$('.messages'),status=$('.status'),form=$('.composer'),input=$('textarea'),sendButton=$('.composer button');
  let token=localStorage.getItem(storageKey)||'',after=0,busy=false,initialized=false,started=false,lastConversation=null,contactCard=null,waitingSince=0,contactFallbackShown=false;const seen=new Set();
  const post=async data=>{const r=await fetch(apiUrl,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,after_id:after,...data})});const j=await r.json();if(j.token&&j.token!==token){token=j.token;localStorage.setItem(storageKey,token)}if(!r.ok||!j.ok)throw new Error(j.error||'request_failed');return j};
  const flatten=b=>{const out=[];(function w(v){if(Array.isArray(v))v.forEach(w);else if(v&&typeof v==='object')out.push(v)})(b);return out};
  const setStatus=(text,kind='')=>{status.className='status'+(kind?' '+kind:'');status.textContent=text};
  const add=m=>{if(seen.has(m.id))return;seen.add(m.id);after=Math.max(after,Number(m.id)||0);const d=document.createElement('div');d.className='msg '+(m.direction==='inbound'?'me':'')+(m.sender_type==='manager'?' manager':'');const t=document.createElement('div');t.textContent=m.text||'';d.appendChild(t);const btns=flatten(m.buttons||[]);if(btns.length){const box=document.createElement('div');box.className='buttons';btns.forEach(b=>{const label=b.text||b.label||'Открыть',url=b.url||b.link||b.href||'';if(url){const a=document.createElement('a');a.textContent=label;a.href=url;a.target='_blank';a.rel='noopener';box.appendChild(a);return}const p=b.callback_data||b.payload||b.data||'';if(!p)return;const bt=document.createElement('button');bt.type='button';bt.textContent=label;bt.onclick=async()=>{bt.disabled=true;try{await sendAction({action:'callback',data:String(p)})}catch(e){bt.disabled=false}};box.appendChild(bt)});if(box.childNodes.length)d.appendChild(box)}const who=document.createElement('div');who.className='who';who.textContent=m.direction==='inbound'?'Вы':(m.sender_type==='manager'?'Менеджер':'AI AnyTour');d.appendChild(who);messages.appendChild(d);messages.scrollTop=messages.scrollHeight};
  const consume=j=>{const chat=j.chat||{};(chat.messages||[]).forEach(add);const c=chat.conversation||null;lastConversation=c;if(!c){setStatus('Онлайн');return}if(c.status==='waiting_manager'){if(c.manager_available===false){waitingSince=0;setStatus('Менеджеры сейчас офлайн','waiting');if(!contactFallbackShown){contactFallbackShown=true;showContact(true)}return}if(!waitingSince)waitingSince=Date.now();setStatus('Ищу свободного менеджера…','waiting');if(!contactFallbackShown&&Date.now()-waitingSince>=90000){contactFallbackShown=true;showContact(true)}return}if(c.status==='manager'){waitingSince=0;if(contactCard&&contactCard.isConnected){contactCard.remove();contactCard=null}setStatus((c.manager_name?c.manager_name:'Менеджер')+' подключён','manager');return}waitingSince=0;setStatus('AI-помощник онлайн')};
  const sendAction=async data=>{if(busy)return;busy=true;sendButton.disabled=true;setStatus(data.action==='profile'?'Сохраняю контакт…':'Готовлю ответ…','typing');try{const j=await post(data);consume(j);return j}catch(e){setStatus('Не удалось отправить. Повторите.','error');throw e}finally{busy=false;sendButton.disabled=false}};
  const init=async()=>{if(initialized)return;initialized=true;setStatus('Подключаемся…','typing');try{const j=await post({action:'init'});consume(j);if(!(j.chat&&j.chat.conversation)&&!started){started=true;consume(await post({action:'start'}))}}catch(e){initialized=false;setStatus('Чат временно недоступен','error')}};
  const poll=async()=>{if(!initialized||busy||!panel.classList.contains('open'))return;try{consume(await post({action:'poll'}))}catch(e){}};
  const open=async()=>{panel.classList.add('open');await init();input.focus();poll()};
  const showContact=async(fallback=false)=>{
    await init();
    if(contactCard&&contactCard.isConnected){contactCard.scrollIntoView({behavior:'smooth',block:'nearest'});return}
    const c=lastConversation||{};
    const card=document.createElement('div');card.className='contact-card';
    card.innerHTML='<div class="ask">Оставить контакт менеджеру</div><div class="hint">Если не хотите ждать, оставьте имя и телефон — менеджер сможет связаться позже. Это необязательно.</div><div class="contact-row"><input class="contact-name" maxlength="120" autocomplete="name" placeholder="Ваше имя"><input class="contact-phone" maxlength="40" inputmode="tel" autocomplete="tel" placeholder="Телефон"></div><div class="contact-actions"><button type="button" class="contact-save">Оставить контакт</button><button type="button" class="contact-skip">Не сейчас</button></div><div class="contact-note"></div>';
    const name=card.querySelector('.contact-name'),phone=card.querySelector('.contact-phone'),note=card.querySelector('.contact-note');name.value=c.display_name||'';phone.value=c.phone||'';
    card.querySelector('.contact-skip').onclick=()=>{card.remove();contactCard=null;input.focus()};
    card.querySelector('.contact-save').onclick=async()=>{const n=name.value.trim(),p=phone.value.trim();note.textContent='';if(!n&&!p){note.textContent='Можно оставить хотя бы имя или телефон.';return}try{await sendAction({action:'profile',name:n,phone:p,email:c.email||''});card.innerHTML='<div class="ask">Спасибо!</div><div class="hint">Контакт сохранён. Менеджер увидит его в карточке диалога.</div>';setTimeout(()=>{if(card.isConnected){card.remove();contactCard=null}},2200)}catch(err){note.textContent=err.message==='invalid_phone'?'Проверьте номер телефона':'Не удалось сохранить. Попробуйте ещё раз.'}};
    messages.appendChild(card);contactCard=card;messages.scrollTop=messages.scrollHeight;setTimeout(()=>name.focus(),50)
  };
  const submitText=async text=>{const value=(text||'').trim();if(!value)return;await init();input.value='';await sendAction({action:'send',text:value}).catch(()=>{input.value=value})};
  launcher.onclick=open;launcherLabel.onclick=open;$('.close').onclick=()=>panel.classList.remove('open');
  root.querySelectorAll('[data-prompt]').forEach(btn=>btn.addEventListener('click',async()=>{await open();const prompt=btn.getAttribute('data-prompt')||'';input.value=prompt;input.focus()}));
  form.onsubmit=async e=>{e.preventDefault();await submitText(input.value)};input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit()}};
  input.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,112)+'px'});
  setInterval(poll,2500);window.AnyTourConsultant={open,close:()=>panel.classList.remove('open')};
})();
