<?php
require_once __DIR__ . '/ConversationDb.php';
require_once __DIR__ . '/MetrikaConversionGoalService.php';
class SalesPipelineService
{
    public static function stages(bool $activeOnly=true): array{$sql='SELECT stage_key,display_name,color,sort_order,is_active,is_terminal,is_won FROM lead_stages'.($activeOnly?' WHERE is_active=1':'').' ORDER BY sort_order,display_name,stage_key';return ConversationDb::connection()->query($sql)->fetchAll();}
    public static function tags(bool $activeOnly=true): array{$sql='SELECT id,tag_key,display_name,color,sort_order,is_active FROM lead_tags'.($activeOnly?' WHERE is_active=1':'').' ORDER BY sort_order,display_name,id';return ConversationDb::connection()->query($sql)->fetchAll();}
    public static function outcomeOptions(): array{return ['open'=>'В работе','won'=>'Продажа','lost'=>'Отказ'];}
    public static function closeReasonOptions(): array{return ['price'=>'Цена','no_contact'=>'Не удалось связаться','changed_plans'=>'Изменились планы','bought_elsewhere'=>'Купил в другом месте','dates'=>'Не подошли даты','destination'=>'Не подошло направление','documents'=>'Документы/ограничения','other'=>'Другое'];}
    public static function stageForConversation(int $id): ?array{$q=ConversationDb::connection()->prepare('SELECT s.stage_key,s.display_name,s.color,s.sort_order,s.is_terminal,s.is_won FROM conversations c LEFT JOIN lead_stages s ON s.stage_key=c.lead_stage_key WHERE c.id=? LIMIT 1');$q->execute([$id]);return$q->fetch()?:null;}
    public static function stageHistoryForConversation(int $id,int $limit=20): array{$limit=max(1,min(100,$limit));$q=ConversationDb::connection()->prepare("SELECT h.id,h.from_stage_key,h.to_stage_key,h.changed_by_manager_id,h.created_at,fs.display_name AS from_stage_name,ts.display_name AS to_stage_name,m.display_name AS changed_by_manager_name FROM lead_stage_history h LEFT JOIN lead_stages fs ON fs.stage_key=h.from_stage_key LEFT JOIN lead_stages ts ON ts.stage_key=h.to_stage_key LEFT JOIN managers m ON m.id=h.changed_by_manager_id WHERE h.conversation_id=? ORDER BY h.id DESC LIMIT {$limit}");$q->execute([$id]);return$q->fetchAll();}
    public static function tagsForConversation(int $id): array{$q=ConversationDb::connection()->prepare('SELECT t.id,t.tag_key,t.display_name,t.color,t.sort_order FROM conversation_lead_tags ct JOIN lead_tags t ON t.id=ct.tag_id WHERE ct.conversation_id=? AND t.is_active=1 ORDER BY t.sort_order,t.display_name,t.id');$q->execute([$id]);return$q->fetchAll();}
    public static function outcomeForConversation(int $id): array{$q=ConversationDb::connection()->prepare('SELECT lead_outcome,lead_close_reason,lead_outcome_note,lead_sale_amount,lead_sale_date,lead_outcome_updated_at,lead_outcome_manager_id FROM conversations WHERE id=? LIMIT 1');$q->execute([$id]);$r=$q->fetch()?:[];return ['outcome'=>(string)($r['lead_outcome']?:'open'),'close_reason'=>$r['lead_close_reason']?:null,'note'=>$r['lead_outcome_note']?:null,'sale_amount'=>$r['lead_sale_amount']!==null?(string)$r['lead_sale_amount']:null,'sale_date'=>$r['lead_sale_date']?:null,'updated_at'=>$r['lead_outcome_updated_at']?:null,'manager_id'=>$r['lead_outcome_manager_id']?:(null)];}
    public static function decorateConversationRows(array $rows): array{if(!$rows)return[];$sm=[];foreach(self::stages(false) as $s)$sm[(string)$s['stage_key']]=$s;$ids=array_values(array_unique(array_filter(array_map(fn($r)=>(int)($r['id']??0),$rows))));$tm=[];$stageSince=[];if($ids){$in=implode(',',array_fill(0,count($ids),'?'));$q=ConversationDb::connection()->prepare("SELECT ct.conversation_id,t.id,t.tag_key,t.display_name,t.color,t.sort_order FROM conversation_lead_tags ct JOIN lead_tags t ON t.id=ct.tag_id WHERE ct.conversation_id IN ({$in}) AND t.is_active=1 ORDER BY t.sort_order,t.display_name,t.id");$q->execute($ids);foreach($q->fetchAll() as $t)$tm[(int)$t['conversation_id']][]=$t;$q=ConversationDb::connection()->prepare("SELECT h.conversation_id,h.created_at FROM lead_stage_history h JOIN (SELECT conversation_id,MAX(id) AS max_id FROM lead_stage_history WHERE conversation_id IN ({$in}) GROUP BY conversation_id) latest ON latest.max_id=h.id");$q->execute($ids);foreach($q->fetchAll() as $h)$stageSince[(int)$h['conversation_id']]=$h['created_at']??null;}foreach($rows as &$r){$id=(int)($r['id']??0);$r['lead_stage']=$sm[(string)($r['lead_stage_key']??'new')]??null;$r['lead_tags']=$tm[$id]??[];$r['lead_stage_since_at']=$stageSince[$id]??null;}unset($r);return$rows;}
    public static function setStage(int $id,string $key,int $actor=0): bool{$key=trim($key);if($id<=0||$key==='')return false;$pdo=ConversationDb::connection();$q=$pdo->prepare('SELECT 1 FROM lead_stages WHERE stage_key=? AND is_active=1 LIMIT 1');$q->execute([$key]);if(!$q->fetchColumn())return false;$q=$pdo->prepare('SELECT lead_stage_key FROM conversations WHERE id=? LIMIT 1');$q->execute([$id]);$current=$q->fetchColumn();if($current===false)return false;$current=(string)$current;if($current===$key)return true;$pdo->beginTransaction();try{$q=$pdo->prepare('UPDATE conversations SET lead_stage_key=? WHERE id=? AND lead_stage_key=?');$q->execute([$key,$id,$current]);if($q->rowCount()!==1){$pdo->rollBack();return self::currentStageKey($id)===$key;}$h=$pdo->prepare('INSERT INTO lead_stage_history (conversation_id,from_stage_key,to_stage_key,changed_by_manager_id) VALUES (?,?,?,?)');$h->execute([$id,$current!==''?$current:null,$key,$actor>0?$actor:null]);$pdo->commit();MetrikaConversionGoalService::salesStage($id,$key);return true;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
    public static function setTags(int $id,array $tagIds,int $actor=0): bool{if($id<=0)return false;$tagIds=array_values(array_unique(array_filter(array_map('intval',$tagIds),fn($v)=>$v>0)));$pdo=ConversationDb::connection();$pdo->beginTransaction();try{$valid=[];if($tagIds){$in=implode(',',array_fill(0,count($tagIds),'?'));$q=$pdo->prepare("SELECT id FROM lead_tags WHERE is_active=1 AND id IN ({$in})");$q->execute($tagIds);$valid=array_map('intval',array_column($q->fetchAll(),'id'));}$pdo->prepare('DELETE FROM conversation_lead_tags WHERE conversation_id=?')->execute([$id]);if($valid){$ins=$pdo->prepare('INSERT INTO conversation_lead_tags (conversation_id,tag_id,added_by_manager_id) VALUES (?,?,?)');foreach($valid as $tid)$ins->execute([$id,$tid,$actor>0?$actor:null]);}$pdo->commit();return count($valid)===count($tagIds);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
    public static function setOutcome(int $id,string $outcome,?string $reason,?string $note,int $actor,?string $saleAmount=null,?string $saleDate=null): bool{
        $outcome=trim($outcome);if(!array_key_exists($outcome,self::outcomeOptions()))return false;$reason=trim((string)$reason);$note=trim((string)$note);
        if($outcome==='lost'&&!array_key_exists($reason,self::closeReasonOptions()))return false;if($outcome!=='lost')$reason='';if(mb_strlen($note)>500)$note=mb_substr($note,0,500);
        $amount=null;$date=null;
        if($outcome==='won'){
            $rawAmount=trim((string)$saleAmount);if($rawAmount!==''){$rawAmount=str_replace(',','.',$rawAmount);if(!is_numeric($rawAmount))return false;$numeric=(float)$rawAmount;if($numeric<0||$numeric>9999999999.99)return false;$amount=number_format($numeric,2,'.','');}
            $rawDate=trim((string)$saleDate);if($rawDate!==''){if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$rawDate))return false;$dt=DateTimeImmutable::createFromFormat('!Y-m-d',$rawDate);if(!$dt||$dt->format('Y-m-d')!==$rawDate)return false;$date=$rawDate;}
        }
        $q=ConversationDb::connection()->prepare('UPDATE conversations SET lead_outcome=?,lead_close_reason=?,lead_outcome_note=?,lead_sale_amount=?,lead_sale_date=?,lead_outcome_updated_at=NOW(),lead_outcome_manager_id=? WHERE id=?');$q->execute([$outcome,$reason!==''?$reason:null,$note!==''?$note:null,$amount,$date,$actor>0?$actor:null,$id]);$ok=$q->rowCount()>0;if($ok&&$outcome==='won')MetrikaConversionGoalService::saleOutcome($id,$outcome);return$ok;
    }
    public static function conversationSnapshot(int $id): array{return ['stage'=>self::stageForConversation($id),'stage_history'=>self::stageHistoryForConversation($id),'tags'=>self::tagsForConversation($id),'outcome'=>self::outcomeForConversation($id)];}
    private static function currentStageKey(int $id): string{$q=ConversationDb::connection()->prepare('SELECT lead_stage_key FROM conversations WHERE id=? LIMIT 1');$q->execute([$id]);return(string)($q->fetchColumn()?:'');}
}
