(()=>{
  const script=document.currentScript;
  const apiUrl=new URL('api.php',script&&script.src?script.src:location.href).toString();
  const storageKey='anytour_consultant_token_v1';
  const host=document.createElement('div');
  host.id='anytour-consultant-host';
  document.body.appendChild(host);
  const root=host.attachShadow({mode:'open'});
  root.innerHTML=`<style>
    *{box-sizing:border-box}.launcher{position:fixed;right:20px;bottom:20px;z-index:2147483000;border:0;border-radius:999px;background:#111827;color:#fff;width:58px;height:58px;font:26px/1 system-ui;box-shadow:0 8px 28px #0003;cursor:pointer}.panel{position:fixed;right:20px;bottom:90px;z-index:2147483000;width:min(390px,calc(100vw - 24px));height:min(620px,calc(100vh - 120px));background:#f5f6f8;border-radius:18px;box-shadow:0 16px 50px #0003;overflow:hidden;display:none;flex-direction:column;font:14px/1.4 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#18202a}.panel.open{display:flex}.head{padding:14px 16px;background:#fff;border-bottom:1px solid #e6e8eb;display:flex;justify-content:space-between;align-items:center}.title{font-weight:700;font-size:16px}.sub{font-size:12px;color:#7b8490}.close{border:0;background:none;font-size:22px;cursor:pointer}.messages{flex:1;overflow:auto;padding:14px;display:flex;flex-direction:column;gap:9px}.msg{max-width:86%;padding:9px 11px;border-radius:14px;background:#fff;white-space:pre-wrap;word-break:break-word}.msg.me{align-self:flex-end;background:#e8f3ff}.msg.manager{background:#dcfce7}.who{font-size:10px;color:#7c8794;margin-top:4px}.buttons{display:flex;flex-direction:column;gap:6px;margin-top:8px}.buttons button,.buttons a{display:block;width:100%;border:1px solid #d8dde3;border-radius:10px;background:#fff;padding:8px 10px;text-align:center;color:#18202a;text-decoration:none;font:inherit;cursor:pointer}.composer{display:flex;gap:7px;padding:10px;background:#fff;border-top:1px solid #e6e8eb}.composer textarea{flex:1;border:1px solid #d8dde3;border-radius:11px;padding:9px 10px;resize:none;min-height:40px;max-height:100px;font:inherit}.composer button{border:0;border-radius:11px;background:#111827;color:#fff;padding:0 14px;font:inherit;cursor:pointer}.status{padding:5px 12px;font-size:11px;color:#7b8490;background:#fff}.error{color:#b42318}@media(max-width:520px){.launcher{right:14px;bottom:14px}.panel{inset:0;width:100vw;height:100vh;border-radius:0}.panel.open{display:flex}}
  </style><button class="launcher" aria-label="Открыть чат">💬</button><section class="panel"><div class="head"><div><div class="title">AnyTour · онлайн-консультант</div><div class="sub">AI + менеджер при необходимости</div></div><button class="close" aria-label="Закрыть">×</button></div><div class="status">Подключаемся…</div><div class="messages"></div><form class="composer"><textarea placeholder="Напишите, куда хотите поехать…"></textarea><button>➤</button></form></section>`;
  const $=s=>root.querySelector(s), launcher=$('.launcher'),panel=$('.panel'),messages=$('.messages'),status=$('.status'),form=$('.composer'),input=$('textarea');
  let token=localStorage.getItem(storageKey)||'', after=0, busy=false, started=false;
  const seen=new Set();
  const post=async data=>{const r=await fetch(apiUrl,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,after_id:after,...data})});const j=await r.json();if(j.token&&j.token!==token){token=j.token;localStorage.setItem(storageKey,token)}if(!r.ok||!j.ok)throw new Error(j.error||'request_failed');return j};
  const flattenButtons=b=>{const out=[];(function walk(v){if(Array.isArray(v))v.forEach(walk);else if(v&&typeof v==='object')out.push(v)})(b);return out};
  const addMessage=m=>{if(seen.has(m.id))return;seen.add(m.id);after=Math.max(after,Number(m.id)||0);const d=document.createElement('div');d.className='msg '+(m.direction==='inbound'?'me':'')+(m.sender_type==='manager'?' manager':'');const text=document.createElement('div');text.textContent=m.text||'';d.appendChild(text);const btns=flattenButtons(m.buttons||[]);if(btns.length){const box=document.createElement('div');box.className='buttons';btns.forEach(b=>{const label=b.text||b.label||'Открыть';const url=b.url||b.link||b.href||'';if(url){const a=document.createElement('a');a.textContent=label;a.href=url;a.target='_blank';a.rel='noopener';box.appendChild(a);return}const payload=b.callback_data||b.payload||b.data||'';if(!payload)return;const bt=document.createElement('button');bt.type='button';bt.textContent=label;bt.onclick=async()=>{bt.disabled=true;try{await sendAction({action:'callback',data:String(payload)})}catch(e){bt.disabled=false}};box.appendChild(bt)});if(box.childNodes.length)d.appendChild(box)}const who=document.createElement('div');who.className='who';who.textContent=m.direction==='inbound'?'Вы':(m.sender_type==='manager'?'Менеджер':'AI');d.appendChild(who);messages.appendChild(d);messages.scrollTop=messages.scrollHeight};
  const consume=j=>{const chat=j.chat||{};(chat.messages||[]).forEach(addMessage);const c=chat.conversation||null;if(c){status.classList.remove('error');status.textContent=c.status==='waiting_manager'?'Запрос передан менеджеру':c.status==='manager'?'Менеджер подключён':'Онлайн'}else status.textContent='Онлайн'};
  const sendAction=async data=>{if(busy)return;busy=true;try{const j=await post(data);consume(j);return j}catch(e){status.textContent='Не удалось отправить. Повторите.';status.classList.add('error');throw e}finally{busy=false}};
  const init=async()=>{try{const j=await post({action:'init'});consume(j);if(!(j.chat&&j.chat.conversation)&&!started){started=true;consume(await post({action:'start'}))}}catch(e){status.textContent='Чат временно недоступен';status.classList.add('error')}};
  const poll=async()=>{if(busy)return;try{const j=await post({action:'poll'});consume(j)}catch(e){}};
  launcher.onclick=()=>{panel.classList.add('open');input.focus();poll()};$('.close').onclick=()=>panel.classList.remove('open');
  form.onsubmit=async e=>{e.preventDefault();const text=input.value.trim();if(!text)return;input.value='';await sendAction({action:'send',text}).catch(()=>{input.value=text})};input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit()}};
  init();setInterval(poll,3000);
  window.AnyTourConsultant={open:()=>panel.classList.add('open'),close:()=>panel.classList.remove('open')};
})();
